name: CI Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    steps:
      - name: Decode Key
        run: |
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo ${{ secrets.SLIIT_EATS_KEY_JKS }} | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/key.jks
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.1.1
        with:
          channel: 'stable'
      - run: flutter upgrade
      - run: flutter build apk --release
        env:
          KEY_PASSWORD: ${{ secrets.SLIIT_EATS_KEY_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.SLIIT_EATS_ALIAS_PASSWORD }}
      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk